name: benchmark-data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pandas
  - pip
  - pytest
  - dask
  - distributed
  - fsspec>=2023
  - h5pyd
  - jupyter
  - matplotlib
  - pre-commit
  - s3fs>=2023.4.0
  - xarray
  - rasterio
  - rioxarray>=0.13.1
  - numpy
  - xesmf
  - pip:
      - git+https://github.com/pangeo-forge/pangeo-forge-recipes.git@beam-refactor
      - git+https://github.com/carbonplan/cmip6-downscaling.git
      - 'apache-beam[interactive, dataframe]'
