name: benchmark-data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - pip
  - pytest
  - dask
  - distributed
  - fsspec>=2023
  - h5pyd
  - jupyter
  - matplotlib
  - pangeo-forge-recipes=0.10.0
  - pre-commit
  - s3fs>=2023.4.0
  - xarray
  - rasterio
  - rioxarray>=0.13.1
  - numpy
  - xesmf=0.7.1
  - pip:
      - git+https://github.com/carbonplan/ndpyramid.git
      - 'apache-beam[aws,interactive,dataframe]'
