name: benchmark-maps
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - coiled
  - distributed
  - hvplot
  - pandas
  - pip
  - pytest
  - requests
  - rich
  - s3fs
  - typing-extensions
  - universal_pathlib
  - pip:
      - pytest-playwright
      - cloud-detect
      - opencv-python
