name: benchmark-maps
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - coiled
  - distributed
  - git
  - hvplot
  - pandas
  - pip
  - jupyter
  - pytest
  - requests
  - rich
  - s3fs
  - typing-extensions
  - universal_pathlib
  - pip:
      - pytest-playwright
      - cloud-detect
      - opencv-python-headless
      - git+https://github.com/carbonplan/benchmark-maps
      - git+https://github.com/scalableminds/zarrita.git@b88ae5ca02917e24e716855f15ffaf020b95bb1a
