name: Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maps:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: set up conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Install browsers
        run: |
          playwright install

      - name: Run benchmarks
        run: |
          python main.py --runs 25 --time-since-last-paint-threshold 800
